### ISSUE TITLE
Repository issue

### ISSUE THREAD

**Issue by petr0808** [XCSoar/xcsoar-data-repository#191]
Hungarian airspace source has been changed from http to https!

**Comment by rawtaz** [comment]
@petr0808 Can you clarify the symptoms - are you saying that XCSoar fails to fetch the Hungarian airspace entirely, or are you just pointing out that it has changed from http to https and that we should update the canonical URL (but XCSoar is still able to fetch the file properly)?

I'm asking because the server redirects from http to https, so in general it does work to fetch the file starting at the http URL, but I'm curious if you mean that XCSoar doesn't follow the redirect.

**Comment by petr0808** [comment]
Dear rawatz,

Usual applications are able to fetch due to forwarding capabilities. On PC,
Android devices it is working fine. But it does not in openvario.

BR,
Peter

**Comment by rawtaz** [comment]
I guess that could be due to OpenVario having an older XCSoar version. Anyway, we'll fix the URL. Thanks for the notice!

**Comment by petr0808** [comment]
Actually I'm testing version 7. Nevertheless I'll check the reason why is
it unable to follow port forward.
